### ISSUE TITLE
Source codes of AppCache are missing

### ISSUE THREAD

**Issue by henan-lujun** [iosptl/ios7ptl#4]
Hi

When I reading the chapter 12 about AppCache, I found it's useful very much. But looks like the AppCache.h and AppCache.m are missing in github which are described in chapter 12.

BTW, these two files are in ptl6 but only for ios6. Could you please update the missing files?

Br
Lu Jun

**Comment by Bareypatch** [comment]
> Hi
> 
> When I reading the chapter 12 about AppCache, I found it's useful very much. But looks like the AppCache.h and AppCache.m are missing in github which are described in chapter 12.
> 
> BTW, these two files are in ptl6 but only for ios6. Could you please update the missing files?
> 
> Br
> Lu Jun
